language: go
sudo: false
go:
- 1.8.3
install:
- go get -t ./...
- go get github.com/nats-io/gnatsd
- go get github.com/nats-io/go-nats
- go get github.com/nats-io/nuid
- go get github.com/fatih/structs
- go get github.com/mitchellh/mapstructure
- go get github.com/stretchr/testify/assert
- go get -u honnef.co/go/tools/cmd/staticcheck
- go get -u honnef.co/go/tools/cmd/gosimple
- go get -u github.com/client9/misspell/cmd/misspell
before_script:
- go fmt ./...
- go vet ./...
- gosimple ./...
script:
- go test -i -race ./...
- go test -v -race ./...